### ISSUE TITLE
Unable to view connection on taskforce.sh/connections

### ISSUE THREAD

**Issue by mannharleen** [taskforcesh/taskforce-connector#40] opened 2021-10-19 06:05 UTC
I am running the following command
```
taskforce -n "myconnection" -t "xxx" -h "yyy" --passwd "zzz"
```

The CLI logs are as follows
```
Taskforce Connector v1.15.0 - (c) 2017-2021 Taskforce.sh Inc.
WebSocket: opening connection to Taskforce.sh
WebSocket: opened connection to Taskforce.sh
WebSocket: received {"id":"xxxx","data":{"res":"connections","cmd":"getConnection"}}
Redis: connected to redis server
WebSocket:  retry in 5000ms
WebSocket: closed [Arguments] { '0': 1006 }
WebSocket: reconnecting...
WebSocket: Unexpected server response: 502
WebSocket:  retry in 5000ms
WebSocket: closed [Arguments] { '0': 1006 }
WebSocket: reconnecting...
WebSocket: opened connection to Taskforce.sh
WebSocket: received {"id":"xxxxxx","data":{"res":"connections","cmd":"getConnection"}}
Redis: connected to redis server
WebSocket:  retry in 5000ms
WebSocket: closed [Arguments] { '0': 1006 }
WebSocket: reconnecting...
WebSocket: Unexpected server response: 502
WebSocket:  retry in 5000ms
WebSocket: closed [Arguments] { '0': 1006 }
WebSocket: reconnecting...
WebSocket: Unexpected server response: 502
WebSocket:  retry in 5000ms
WebSocket: closed [Arguments] { '0': 1006 }
WebSocket: reconnecting...
```

**Comment by manast** [comment] 2021-10-19 06:28
It is up again. Please can you recheck?

**Comment by RickyHolland** [comment] 2022-01-13 11:49
Also having this issue, connections are not showing up in the taskforce.sh dashboard.

`taskforce -t ttt -n dev -h hhh -p 6379 --passwd ppp`

```
Taskforce Connector v1.15.0 - (c) 2017-2021 Taskforce.sh Inc.
WebSocket: opening connection to Taskforce.sh
WebSocket: opened connection to Taskforce.sh
WebSocket: received {"id":"881f2259-d0ce-49ab-aeac-994e2439cee2","data":{"res":"connections","cmd":"getConnection"}}
Redis: connected to redis server
```

We have paid for a subscription so initially I was trying to get it to work by specifying a particular Team but have taken that out of the equation to see if that was the cause of the issue but still no connections are showing in the dashboard.

![image](https://user-images.githubusercontent.com/22330292/149325061-60c1eefa-851e-4b37-a150-c8eae16ca640.png)

**Comment by RickyHolland** [comment] 2022-01-13 13:02
Appears our issue is due to lack of support for BullMQ within the connector, can you confirm if support is on the roadmap? As we are keen to evaluate the product further.

**Comment by manast** [comment] 2022-01-17 05:05
The connector supports both Bull and BullMQ, so that should not be the problem here 🤔

**Comment by RickyHolland** [comment] 2022-01-17 13:51
Ah, we had assumed that only Bull support was available in the connector based upon the README in the repo.

To return to the original issue, we have deployed the connector with it targeting a standard AWS Elasticache (Redis) server. As the above logs show, the connector is seemingly able to connect to its own backend (taskforce.sh) and also the target Redis server in question. But when looking in the tasforce.sh GUI we do not see any connections showing up, even if leaving for some time.

I had tried using the last view versions of the connector agent. Could you please advise if there are any further logs available that we can use to troubleshoot further?

**Comment by manast** [comment] 2022-01-17 13:57
Can you double-check that you are using the correct token? It looks as it is connecting correctly but to a different account than the one that you are logged in to.

**Comment by RickyHolland** [comment] 2022-01-17 14:06
Hmm strange, sure I'll use a freshly generated API token.

**Comment by RickyHolland** [comment] 2022-01-25 17:22
Finally had chance to take another look at this. I've created a freshly generated token and configured as such on the Connector but unfortunately I'm still unable to see any connections in the Dashboard, even though the logs suggest connectivity to Taskforce.sh and Redis are fine.

`Taskforce Connector v1.15.0 - (c) 2017-2021 Taskforce.sh Inc.
WebSocket: opening connection to Taskforce.sh
WebSocket: opened connection to Taskforce.sh
WebSocket: received {"id":"50bef31f-20f2-4e2d-b47f-e2714dc533e5","data":{"res":"connections","cmd":"getConnection"}}
Redis: connected to redis server`

I've double checked that the new API token is correct.

For context I'm supplying the name "Dev" for this connection and assigning it to the team "DevOps".

**Comment by manast** [comment] 2022-01-26 00:35
Does the team DevOps exist? and do you get the same problem with a different connection name and no team?

**Comment by RickyHolland** [comment] 2022-01-26 11:02
Hi @manast, Yes to confirm the team DevOps does exist. I tried with a different connection name this morning (still using the Team) and instantly all was working as expected (I can see the connection in the dashboard). I then tried reverting the name back and the connection is still working. Very strange.

But thanks for your help, we can now evaluate the product.

**Comment by manast** [comment] 2022-01-26 14:36
Ok, let's close this issue for now then.

**Closed by manast** 2022-01-26 14:36 UTC
