### ISSUE TITLE
Keeps making Redis connections

### ISSUE THREAD

**Issue by Slaventsiy** [taskforcesh/taskforce-connector#2] opened 2018-04-09 08:43 UTC
The number of connections to Redis keeps growing over time and the connections are not closed.

**Comment by IvanMMM** [comment] 2019-02-04 13:11
Met this some time ago, can confirm.

**Comment by manast** [comment] 2019-02-04 20:20
There is a new taskforce-connector release (v1.1.1) that is closing one connection that was not closed properly before, would you mind to test with this one to see if the issue is resolved?

**Comment by manast** [comment] 2019-09-08 19:29
Will close due to lack of feedback.

**Closed by manast** 2019-09-08 19:29 UTC
Labels: bug
